name: Docker Build & Compose Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start Docker Compose services
      run: docker compose up -d --build

    - name: Check running containers
      run: docker compose ps

    - name: View server logs
      run: docker compose logs server

    - name: View client logs
      run: docker compose logs client

    - name: Stop Docker Compose services
      if: always()
      run: docker compose down
